### ISSUE TITLE
Doesn't recognize shell meta-characters in file path

### ISSUE THREAD

**Issue by ankush981** [herrfugbaum/qsv#12]
When passing the CSV path an a string, qsv doesn't seem to recognize the tilde "~" character on Linux (Ubuntu 18.04). Here's the command history to show how to reproduce the bug:

```
qsv$ node bin/qsv.js -p "~/Desktop/data.csv" -h
{ [Error: ENOENT: no such file or directory, open '~/Desktop/data.csv']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/Desktop/data.csv' }
(node:16684) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:258:10)
    at WriteStream.Writable.write (_stream_writable.js:292:21)
    at start (/media/common/code/projects/github/qsv/bin/qsv.js:23:20)
(node:16684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
qsv$ node bin/qsv.js -p "/home/ankush/Desktop/data.csv" -h
QSV>
```

**Comment by herrfugbaum** [comment]
Thanks for the report!

Afaik node.js doesn't expand meta characters automatically see https://github.com/nodejs/node/issues/684

But there is a package linked in the issue that looks promising: [untildify](https://github.com/sindresorhus/untildify)

**Comment by ankush981** [comment]
Damn. I saw something interesting in the link you shared: https://github.com/nodejs/node/issues/684#issuecomment-302413878. But then, who knows what other characters we might encounter later!

**Comment by herrfugbaum** [comment]
I just tested the version of #14 with ~ and $ and it seems to work

```bash
test=path/to/file.csv

node bin/qsv.js -p ~/$test
```

![default](https://user-images.githubusercontent.com/12859776/49161218-b07ca400-f328-11e8-929c-3cddfa16936d.jpg)


I don't know if there are more meta characters of interest.
If we find some it's probably best to open an issue/pr on the untildify repo.
What do you think?
